### ISSUE TITLE
Failed to run custom build command for zephyr-sys v0.1.0

### ISSUE THREAD

**Issue by Kylof61034** [tylerwhall/zephyr-rust#50]
Hey there,
I am currently trying to build the sample rust app, but I always end up with this error:
```
"error: failed to run custom build command for `zephyr-sys v0.1.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/zephyr-sys)`"
```

### My Command

```
RUST_BACKTRACE=1 west build -p auto -b qemu_x86 samples/rust-app/
```

### Some information about my setup

- sdk version: 0.12.2
- zephyr version: 2.4.0
- env variables:
  - WEST_BASE=~/Documents/zephyr-rust/zephyrproject
  - ZEPHYR_BASE=~/Documents/zephyr-rust/zephyrproject/zephyr
- zephyr-rust verison: last commit on master
- zephyr-rust location: ~/Documents/zephyr-rust/zephyrproject/zephyr-rust

### Full output
```
[1/28] Performing build step for 'rust_project'
FAILED: modules/zephyr-rust/src/rust_project-stamp/rust_project-build modules/zephyr-rust/app/i686-unknown-zephyr/release/librust_app.a /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/src/rust_project-stamp/rust_project-build /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/app/i686-unknown-zephyr/release/librust_app.a 
cd /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust && env ZEPHYR_BINDGEN=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/zephyr-bindgen/release/zephyr-bindgen ZEPHYR_KERNEL_VERSION_NUM=0x20400 CONFIG_USERSPACE=y CONFIG_RUST_ALLOC_POOL=y CONFIG_RUST_MUTEX_POOL=y CONFIG_POSIX_CLOCK= "TARGET_CFLAGS=-I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/include -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/zephyr/include/generated -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/soc/x86/ia32 -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/lib/libc/minimal/include -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/uart-buffered/src -DKERNEL -D__ZEPHYR__=1 -D_FORTIFY_SOURCE=2 -DBUILD_VERSION=zephyr-v2.4.0 -isystem/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/lib/libc/minimal/include -imacros /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/zephyr/include/generated/autoconf.h --target=i686-unknown-linux-gnu" SYSROOT=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot SYSROOT_BUILD=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build APP_BUILD=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/app RUST_TARGET=i686-unknown-zephyr RUST_TARGET_SPEC=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/targets/i686-unknown-zephyr.json CARGO_MANIFEST=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/rust-app/Cargo.toml ./build.sh
       Fresh core v0.0.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/core)
       Fresh rustc-std-workspace-core v1.99.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/rustc-std-workspace-core)
       Fresh compiler_builtins v0.1.91
       Fresh alloc v0.0.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/alloc)
       Fresh unicode-xid v0.1.0
       Fresh proc-macro2 v0.4.30
       Fresh libc v0.2.138 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/libc)
       Fresh cfg-if v1.0.0
       Fresh cc v1.0.79
   Compiling rustc-std-workspace-alloc v1.99.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/rustc-std-workspace-alloc)
       Fresh time-convert v0.1.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/zephyr-core/time-convert)
       Fresh rustc-demangle v0.1.21
       Fresh quote v0.6.13
   Compiling zephyr-sys v0.1.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/zephyr-sys)
   Compiling panic_abort v0.0.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/panic_abort)
     Running `rustc --crate-name rustc_std_workspace_alloc --edition=2021 /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/rustc-std-workspace-alloc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=729f322b1b601942 -C extra-filename=-729f322b1b601942 --out-dir /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps --target /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/targets/i686-unknown-zephyr.json -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/release/deps --extern alloc=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/liballoc-74c7dd9e312f36d2.rmeta -Cembed-bitcode=yes`
       Fresh syn v0.15.44
     Running `/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/release/build/zephyr-sys-069c120b03fd699d/build-script-build`
       Fresh derive_more v0.14.1
       Fresh unwind v0.0.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/unwind)
     Running `rustc --crate-name panic_abort --edition=2021 /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/panic_abort/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=a5c7464b892f9767 -C extra-filename=-a5c7464b892f9767 --out-dir /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps --target /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/targets/i686-unknown-zephyr.json -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/release/deps --extern alloc=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/liballoc-74c7dd9e312f36d2.rmeta --extern cfg_if=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/libcfg_if-c54525e4a6398059.rmeta --extern compiler_builtins=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/libcompiler_builtins-b15572c7d1d45909.rmeta --extern core=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/libcore-fcff41cc0cbb84e0.rmeta --extern libc=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/liblibc-bc0b80b3116097b0.rmeta -Cembed-bitcode=yes`
   Compiling hashbrown v0.12.3
   Compiling std_detect v0.1.5 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/stdarch/crates/std_detect)
     Running `rustc --crate-name hashbrown --edition=2021 /home/markus/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="compiler_builtins"' --cfg 'feature="core"' --cfg 'feature="nightly"' --cfg 'feature="rustc-dep-of-std"' --cfg 'feature="rustc-internal-api"' -C metadata=95f03c2318d1470b -C extra-filename=-95f03c2318d1470b --out-dir /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps --target /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/targets/i686-unknown-zephyr.json -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/release/deps --extern compiler_builtins=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/libcompiler_builtins-b15572c7d1d45909.rmeta --extern alloc=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/librustc_std_workspace_alloc-729f322b1b601942.rmeta --extern core=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/librustc_std_workspace_core-82ddcf49924cf945.rmeta --cap-lints allow -Cembed-bitcode=yes`
     Running `rustc --crate-name std_detect --edition=2018 /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/rust/library/stdarch/crates/std_detect/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="compiler_builtins"' --cfg 'feature="core"' --cfg 'feature="rustc-dep-of-std"' -C metadata=ac52666c92a9ce12 -C extra-filename=-ac52666c92a9ce12 --out-dir /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps --target /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/targets/i686-unknown-zephyr.json -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps -L dependency=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/release/deps --extern cfg_if=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/libcfg_if-c54525e4a6398059.rmeta --extern compiler_builtins=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/libcompiler_builtins-b15572c7d1d45909.rmeta --extern alloc=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/librustc_std_workspace_alloc-729f322b1b601942.rmeta --extern core=/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/i686-unknown-zephyr/release/deps/librustc_std_workspace_core-82ddcf49924cf945.rmeta -Cembed-bitcode=yes`
error: failed to run custom build command for `zephyr-sys v0.1.0 (/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/zephyr-sys)`

Caused by:
  process didn't exit successfully: `/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/modules/zephyr-rust/sysroot-build-stage1/release/build/zephyr-sys-069c120b03fd699d/build-script-build` (exit status: 101)
  --- stderr
  cflags: -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/include -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/zephyr/include/generated -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/soc/x86/ia32 -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/lib/libc/minimal/include -I/home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/uart-buffered/src -DKERNEL -D__ZEPHYR__=1 -D_FORTIFY_SOURCE=2 -DBUILD_VERSION=zephyr-v2.4.0 -isystem/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/lib/libc/minimal/include -imacros /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build/zephyr/include/generated/autoconf.h --target=i686-unknown-linux-gnu
  userspace: true
  thread 'main' panicked at '"_dnode_union_(anonymous_at_/home/markus/Documents/zephyr-rust/zephyrproject/zephyr/include/sys/dlist_h_32_2)" is not a valid Ident', /home/markus/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
     2: proc_macro2::fallback::Ident::_new
     3: proc_macro2::Ident::new
     4: bindgen::ir::context::BindgenContext::rust_ident
     5: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
     6: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
     7: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
     8: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
     9: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    10: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    11: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    12: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    13: bindgen::ir::context::BindgenContext::gen
    14: bindgen::Builder::generate
    15: zephyr_bindgen::main
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread 'main' panicked at 'assertion failed: rc.success()', /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/rust/zephyr-sys/build.rs:11:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
     2: core::panicking::panic
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
     3: build_script_build::main
               at ./build.rs:11:5
     4: core::ops::function::FnOnce::call_once
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/markus/Documents/zephyr-rust/zephyrproject/zephyr-rust/build
```

What am I missing here?

**Comment by Kylof61034** [comment]
I managed to build the sample on another machine.
No clue why I didnt work on my main machine tho.
